%YAML 1.1
---
pcap:
  - interface: br0
    threads: 1
    checksum-checks: yes
    bpf-filter: "not net 169.254.254.0/24"
  - interface: br2
    threads: 1
    checksum-checks: yes
    bpf-filter: "not net 169.254.254.0/24"
